export ENV=dev
export GCP_PROJECT=aster-data-platform
export LOG_LEVEL=DEBUG

get-content:
# @python -c "from src.operator.http import PasteBinOperator; PasteBinOperator().execute(request={'data':{'request_type': 'get-content', 'id': 'yqNkp3mR'}})"
	@python -c "from src.operator.http import PasteBinOperator; PasteBinOperator().execute(request={'data':{'request_type': 'get-content', 'id': 'vNrgNqbd'}})"
