name: Validate packages

on: [pull_request]

jobs:
  package_validate:
    strategy:
      matrix:
        package: [airless-core, airless-pdf]
    uses: ./.github/reusable-workflow/package-validate.yml
    with:
      package: ${{ matrix.package }}
