name: Validate packages

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: [ main ]

jobs:
  package_validate:
    strategy:
      matrix:
        package: [airless-core, airless-pdf]
    uses: ./.github/workflows/package-validate-reusable-workflow.yml
    with:
      package: ${{ matrix.package }}
